name: Deploy Service

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: DigitalOcean App Platform deployment
        # You may pin to the exact commit or the version.
        # uses: digitalocean/app_action@e583e1b463e8ac378854c0a01af1de8a5afd836b
        uses: digitalocean/app_action@v1.1.5
        with:
          # Name of the app. (The name of the app must be unique across all apps in the same account.)
          app_name: rel-kurzumfrage
          # DigitalOcean Personal Access Token.(use https://docs.digitalocean.com/reference/api/create-personal-access-token/ for creating new token)
          token: ${{ secrets.DO_ACCESS_TOKEN }}
